name: findingchart_macapp
options:
  bundleIdPrefix: org.transientfinderchart
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "0.1.0"
    ENABLE_HARDENED_RUNTIME: YES
targets:
  findingchart_macapp:
    type: application
    platform: macOS
    sources:
      - path: Sources/findingchart_macapp
    info:
      path: Sources/findingchart_macapp/Info.plist
      properties:
        CFBundleName: findingchart_macapp
        CFBundleDisplayName: Transient Finderchart
        LSMinimumSystemVersion: "14.0"
        NSHumanReadableCopyright: "TransientFinderchart"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.transientfinderchart.findingchart_macapp
        CODE_SIGN_ENTITLEMENTS: ""
